language: node_js
node_js:
  - 'node'

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      script:
        - yarn test

    - stage: build
      script:
        - yarn build
